/**
 * COSMIC PROJECT
 * Foreign function C module
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>

// #include "main.hpp"

#if defined(WIN32) || defined(_WIN32)
#define EXPORT _declspec(dllexport)
#else
#define EXPORT
#endif

#ifdef __cplusplus
extern "C"
{
#endif

    EXPORT const char *get_test_string(void)
    {
        const char *hello = "This string of text was generated by C, not NodeJS.";
        return hello;
    }

    EXPORT const char *handleMessage(int argc, char **argv)
    {
        const char *output = (char *)malloc(512);

        return output;
    }

    EXPORT void testOutput(void)
    {
        printf("hello c console\n");
    }

    // external free
    EXPORT void xfree(void *thing)
    {
        free(thing);
    }

    EXPORT char *randomWhitespace(char *str, int size)
    {
        // Add random invisible whitespace characters to string

        char *newstr = (char *)malloc(size * 2);
        float x;

        for (int i = 0; i < size; i++)
        {
            x = (float)rand() / (float)(RAND_MAX / 1);
            newstr[i] = str[i];

            if (x <= 0.2)
            {
                newstr[i + 1] = '\u034f';
                i++;
            }
            else if (x <= 0.4)
            {
                newstr[i + 1] = '\u200b';
                i++;
            }
            else if (x <= 0.8)
            {
                newstr[i + 1] = '\u2006';
                i++;
            }
        }

        return newstr;
    }
#ifdef __cplusplus
}
#endif
