/**
 * COSMIC PROJECT
 * Foreign function C module
 */

#include <stdio.h>
#include <stdlib.h>

#include "main.h"

char* get_test_string(void) {
    char* hello = "This string of text was generated by C, not NodeJS.";
    return hello;
}

char* handleMessage(int argc, char** argv) {
    char* output = "";
    if (strcmp(argv[0], "*help")) {
        output = "hello";
        return output;
    }
}
