/**
 * COSMIC PROJECT
 * Foreign function C module
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "main.h"

const char *get_test_string(void)
{
    const char *hello = "This string of text was generated by C, not NodeJS.";
    return hello;
}

const char *handleMessage(int argc, char **argv)
{
    const char *output = "";

    return output;
}

void testOutput(void)
{
    printf("hello c console\n");
}
