/**
 * COSMIC PROJECT
 * Foreign function C module
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// #include "main.hpp"

#if defined(WIN32) || defined(_WIN32)
#define EXPORT _declspec(dllexport)
#else
#define EXPORT
#endif

#ifdef __cplusplus
extern "C"
{
#endif

    EXPORT const char *get_test_string(void)
    {
        const char *hello = "This string of text was generated by C, not NodeJS.";
        return hello;
    }

    EXPORT const char *handleMessage(int argc, char **argv)
    {
        const char *output = (char *)malloc(512);

        return output;
    }

    EXPORT void testOutput(void)
    {
        printf("hello c console\n");
    }

    // external free
    EXPORT void xfree(void *thing)
    {
        free(thing);
    }

#ifdef __cplusplus
}
#endif
