/**
 * COSMIC PROJECT
 * Foreign function C module
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "main.h"

const char* get_test_string(void) {
    const char* hello = "This string of text was generated by C, not NodeJS.";
    return hello;
}

const char* handleMessage(int argc, char** argv) {
    const char* output = "";
    printf("%s", argv[0]);

    if (strcmp(argv[0], "*help")) {
        output = "hello";
    } else {
        output = "nothing";
    }

    return output;
}
