default:
    canSetPermissions: false
    canSetAllPermissions: false
    canGenerateKeys: true
    canGenerateInfiniteKeys: false

admin:
    canSetPermissions: true
    canSetAllPermissions: true
    canGenerateKeys: true
    canGenerateInfiniteKeys: true
